---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: infra
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-adapter
  namespace: infra
spec:
  interval: 5m # The interval at which to reconcile the Helm release
  releaseName: prometheus-adapter
  chart:
    spec:
      chart: prometheus-adapter
      version: 4.10.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    prometheus:
      url: http://prometheus-server.infra.svc.cluster.local
      port: 80
    rules:
      default: false
      custom:
      - seriesQuery: '{__name__=~"^istio_requests_total$", destination_workload_namespace!="", destination_app!="", pod!="", reporter="destination"}'
        resources:
          overrides:
            destination_workload_namespace:
              resource: namespace
            destination_app:
              resource: deployment
            pod:
              resource: pod
        name:
          matches: ^(.*)
          as: "requests_per_second"
        metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
      - seriesQuery: '{__name__=~"^DCGM_FI_DEV_GPU_UTIL$", app="nvidia-dcgm-exporter", container="service", service="nvidia-dcgm-exporter"}'
        resources:
          overrides:
            exported_namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: DCGM_FI_DEV_GPU_UTIL
          as: "gpu_utilization"
        metricsQuery: avg(avg_over_time(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)
