{{- if and .Values.exposeModel .Values.exposeModel.enabled }}
{{- if and .Values.exposeModel.jwtVerify .Values.exposeModel.jwtVerify.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ .Release.Name }}-predictor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: isvc.{{ .Release.Name }}-predictor
  jwtRules:
{{- include "serviceAuth.jwt_jwksuri_issuer" . | nindent 2 }}
{{- end }}
{{- end }}

