---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kserve
  namespace: infra
spec:
  type: "oci"
  interval: 10m
  url: oci://ghcr.io/kserve/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-crd
  namespace: infra
spec:
  interval: 5m # The interval at which to reconcile the Helm release
  timeout: 10m
  releaseName: kserve-crd
  chart:
    spec:
      chart: kserve-crd
      version: v0.14.0
      sourceRef:
        kind: HelmRepository
        name: kserve
      interval: 10m
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kserve-resources
  namespace: infra
spec:
  interval: 5m # The interval at which to reconcile the Helm release
  timeout: 10m
  releaseName: kserve-resources
  chart:
    spec:
      chart: kserve
      version: v0.14.1 # https://github.com/kserve/kserve/releases
      sourceRef:
        kind: HelmRepository
        name: kserve
      interval: 10m
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    kserve:
      controller:
        deploymentMode: "RawDeployment"