# kubectl  get cm prometheus-adapter -oyaml
apiVersion: v1
data:
  config.yaml: |
    rules:
    - metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)'
      name:
        matches: "istio_requests_total"
        as: "requests_per_second"
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      seriesQuery: istio_requests_total{pod!="", namespace!=""}
kind: ConfigMap
metadata:
  name: prometheus-adapter
  namespace: default
