# kubectl  get hpa -n test podinfo -oyaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
  namespace: test
spec:
  maxReplicas: 20
  metrics:
  - pods:
      metric:
        name: requests_per_second 
      target:
        averageValue: 3
        type: Value
    type: Pods
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
